import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'README',
    {
      type: 'category',
      label: 'Configure Server',
      items: ['configure-server/mcp-auth', 'configure-server/bearer-auth'],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['tutorials/todo-manager/README'],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'autogenerated',
          dirName: 'references',
        },
      ],
    },
  ],
};

export default sidebars;
